version: "3.8"
services:
  fastapi:
    build: .
    ports:
      - "80:80"
    command: uvicorn main:app --host 0.0.0.0 --port 80
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-O", "-", "http://localhost:80/healthcheck"]